CREATE TABLE IF NOT EXISTS `phpvms_efassflightdata` (
  `id_rec` int(11) NOT NULL AUTO_INCREMENT,
  `idefassflight` varchar(50) NOT NULL DEFAULT '',
  `time` time NOT NULL,
  `lat` varchar(15) NOT NULL DEFAULT '',
  `lon` varchar(15) NOT NULL DEFAULT '',
  `alt` varchar(6) NOT NULL DEFAULT '',
  `ias` int(11) NOT NULL,
  `gs` int(11) NOT NULL,
  `vs` varchar(8) NOT NULL DEFAULT '',
  `galt` varchar(6) NOT NULL DEFAULT '',
  `hdg` smallint(6) NOT NULL,
  `qnh` smallint(4) NOT NULL,
  `sq` smallint(4) NOT NULL,
  `stage` varchar(255) NOT NULL DEFAULT '',
  `l_ldg` tinyint(1) NOT NULL,
  `l_str` tinyint(1) NOT NULL,
  `l_bea` tinyint(1) NOT NULL,
  `l_nav` tinyint(1) NOT NULL,
  `l_gnd` tinyint(1) NOT NULL,
  `l_log` tinyint(1) NOT NULL,
  PRIMARY KEY (`id_rec`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;